version: '3.9'

services:
  frontend:
    build:
      contenxt : ./ui-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui-service:/UI-app
    depends_on:
      - backend

  backend:
    build: 
      context: ./ai-service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./ai-service:/AI-app